Stuyk/rebar-altv

docs/api/server/config.md
src/main/server/config/index.ts

Added an ability to extend Rebar's config. You can init a variable from env, set it manually in runtime.

Improved useConfig, added docs to cover it's usage

---

docs/api/server/document/document-account.md
docs/api/server/document/document-character.md
docs/api/server/document/document-vehicle.md
docs/api/server/events/events.md
docs/api/server/events/index.yml
docs/api/server/player/player-status.md
docs/changelog.md
package.json
src/main/server/document/account.ts
src/main/server/document/character.ts
src/main/server/document/vehicle.ts
src/main/server/events/index.ts
src/main/server/index.ts
src/main/server/player/status.ts
src/main/server/systems/messenger.ts

-   Added `isValid` to `character`, `account`, and `vehicle` documents to check if an entity has a bound document
-   Added `useStatus` to `player` API pathway to check for `account` and `character` status
-   Added `events` to the `Rebar` API
-   Added on account bound
-   Added on character bound
-   Added on vehicle bound
-   Added on message
-   Fixed small bug with case-sensitive commands
-   Fixed bug that allowed sending messages when a `character` was not bound
-   Added `isValid` examples to `character`, `account`, and `vehicle`.
-   Added `useStatus` to `player` section
-   Added `events` section to Server API

feat: system events, document checking, etc.

---

docs/changelog.md
docs/webview/composables/use-local-storage.md
package.json
src/main/client/webview/index.ts
src/main/shared/events/index.ts
webview/composables/useLocalStorage.ts

- Updated `upgrade` script to prevent overwriting tailwind config, or vite config
- Added `useLocalStorage` composable for getting / storing data
- Added `useLocalStorage` composable docs
Closes #21

feat: useLocalStorage Composable

---

docs/api/server/controllers/marker.md
docs/api/server/controllers/textlabel.md
src/main/server/controllers/markers.ts
src/main/server/controllers/textlabel.ts

user can specify the distance to show markers and Text label. if the specified value is greater than 50 it will reset to default value of 50.

Dynamic Max Distance for  Global Markers and  Global Textlabel

---

docs/api/server/systems/useServerWeather.md
docs/changelog.md
package.json
pnpm-lock.yaml
src/main/client/player/camera.ts
src/main/server/controllers/interaction.ts
src/main/server/database/index.ts
src/main/server/events/index.ts
src/main/server/index.ts
src/main/server/systems/serverWeather.ts

- Update dependencies
- Update `_id` in database functions to use a non-deprecated ObjectId handler
- Added `useServerWeather` function to allow setting weather and weather forecast
- This does not automatically sync for players, it's just a global way to set the data
- Added `useServerWeather` docs
Closes #29

feat: useServerWeather, update deps, fix _id deprecation

---

docs/changelog.md
docs/plugins/what-is-a-plugin.md
docs/webview/composables/use-audio.md
docs/webview/composables/use-events.md
docs/webview/composables/use-local-storage.md
docs/webview/composables/use-messenger.md
docs/webview/composables/use-minimap.md
docs/webview/composables/use-player-stats.md
package.json
scripts/upgrade.js
src/main/client/menus/native/input.ts
tsconfig.json
webview/src/main.ts
webview/vite.config.ts

- Added `@Composables` path alias
- Added `@Plugins` path alias
- Updated composables with `@Composables`
- Updated `what is a plugin` with information about component / composable only plugins

feat: composable and plugin path aliases

---

src/main/server/vehicle/index.ts

Added Front/Back Wheels to mod loading

Update vehicle mod-loading (wheels)

---

src/main/client/system/stats.ts
src/main/shared/events/index.ts
webview/composables/usePlayerStats.ts

Added the vehicle lockState to usePlayerStats composable.

Added Vehicle lockState to usePlayerStats

---

src/main/server/database/index.ts

This PR adds an `aggregate` function to allow developers to run aggregation queries. These queries allow returning computed results with all computations running on the database.
https://www.mongodb.com/docs/manual/aggregation/

feat: add aggregate db operation

---

src/main/client/controllers/blip.ts
src/main/client/player/controls.ts
src/main/client/player/index.ts
src/main/client/system/index.ts
src/main/client/system/world.ts
src/main/client/virtualEntities/marker.ts
src/main/server/player/world.ts
src/main/shared/events/index.ts
src/main/shared/translate.ts
src/main/shared/types/blip.ts
src/main/shared/types/marker.ts

- Blip route (assigning a routeColor. will enable a route to the blip).
- Exposed controls functions on client.
- Added some RPC methods to get current position details and travel distance between points.
- Added some Marker properties - `bobUpAndDown`, `faceCamera`, `rotate`.
- Added a possibility to make a translation template and pass context inside:
- Example of usage:
```typescript
const { t, setBulk } = useTranslate();
setBulk({ 
en: { 
'dummy': 'Hello, {{ name }}.' 
} 
});
t('dummy', { name: "Stuyk" });
// Hello, Stuyk.
```

Added some enhancements for Blip, Marker. Extra world RPC getters. Translation template context.

---

docs/api/server/controllers/interaction.md
docs/changelog.md
package.json
src/main/client/controllers/index.ts
src/main/client/controllers/interactionLocal.ts
src/main/server/controllers/interactionLocal.ts
src/main/server/index.ts
src/main/shared/events/index.ts

-   Added `useInteractionLocal` to create local interactions for individual players
-   Updated `useInteraction` to include `useInteractionLocal`

feat: local interactions, closes #66

---

package.json
pnpm-lock.yaml
scripts/restart.js
src/main/server/rpc/index.ts
src/main/server/startup.ts

-   Added an RPC endpoint under `http://127.0.0.1:8787` with endpoints `/restart`, `/`, and `/health`.
-   Fixed issue where reconnecting too early would cause client to be frozen on reconnecting
-   Restarting server now kicks all players while in dev mode only

feat: rpc server, fix reconnect issues

---

docs/changelog.md
package.json
scripts/restart.js
src/main/client/index.ts
src/main/client/screen/instructionalButtons.ts
src/main/server/controllers/instructionalButtons.ts
src/main/server/controllers/interaction.ts
src/main/server/database/index.ts
src/main/server/document/increment.ts
src/main/server/index.ts
src/main/server/rpc/admin/index.ts
src/main/server/rpc/api/index.ts
src/main/server/rpc/index.ts
src/main/server/rpc/server/index.ts
src/main/server/startup.ts
src/main/server/systems/vscodeTransmitter.ts
src/main/shared/events/index.ts
src/main/shared/types/index.ts
src/main/shared/types/instructionalButtons.ts

-   Updated RPC endpoints
-   Began structuring new RPC endpoint functions

feat: additional rpc endpoints, wip

---

docs/changelog.md
package.json
scripts/upgrade.js

-   Auto copy `nodemon-dev` and `nodemon-hot` files during script updates

feat: fix copying nodemon-dev, and nodemon-hot files

---

docs/useRebar/systems/useServerConfig.md
src/main/client/system/serverConfig.ts
src/main/shared/types/serverConfig.ts

Thanks to the code snipped from Garcia on the Rebar Discord, i added disableing the Wheel Radial Menu into serverConfig.

Added disabling Wheel Radial Menu into serverConfig.

---

src/main/client/system/serverKeypress.ts
src/main/server/systems/serverKeypress.ts
src/main/shared/events/index.ts

Adds the new callback "hold" to useKeypress which is triggered when the specified key is held down.

Add new callback "hold" to useKeypress

---

src/main/server/player/audio.ts
src/main/shared/events/index.ts
webview/composables/useAudio.ts

I added:
- stopAudio function to be able to stop the current running Audio instance.
- Missing volume arg from my last Pull for playSound function

Added stopAudio, added missing Volume arg

---

webview/src/components/Development.vue

This PR enhances the Dev Menu by adding a scrollable feature to improve usability when dealing with a large number of pages.

Add scrollable functionality to Dev Menu

---

src/main/server/vehicle/index.ts

Should resolve all bugs, related to loading of custom colors.

Color logic was broken

---

src/main/server/player/animation.ts

blend durations, playback rate, and duration in milliseconds

Refactor animation functions to include optional parameters

---

src/main/server/getters/player.ts
src/main/server/getters/vehicle.ts

- Results are consistently sorted by distance to improve reliability

refactor: Update player and vehicle getters to use alt.Utils for consistent entity retrieval

---

src/main/server/systems/permissions/permissionProxy.ts

The Events which triggered were not the same as in the Docs nor from the interface.
With this PR this should be fixed

fix: events for Permissions
